### ISSUE TITLE
facilitating slower enumeration 

### ISSUE THREAD

**Issue by audibleblink** [ropnop/kerbrute#16]
In your opinion, if one was to implement the ability to go slow, what would be your preference be for the interface?:

1. Allow subcommands to also accept  one-off entries, then a user can bash loop around kerbrute
  ```bash
while read name; do
  sleep 5
  kerbrute userenum --dc kdc.site.com -d site.com --username "${name}"
done < names.txt
  ```

2. Add something like `--delay <seconds>` flag
  ```bash
kerbrute --delay 5 userenum --dc kdc.site.com -d site.com names.txt
  ```

3. Do nothing and rely on bash trickery:
  ```bash
while read name; do
  sleep 5
  kerbrute userenum --dc kdc.site.com -d site.com <(<<<"${name}")
done < names.txt
  ```

**Comment by ropnop** [comment]
Hey! Thanks for the  question. I don't love options 1 or 3 since every time you start kerbrute it looks up the Domain Controller. Doesn't make a huge difference I know, but it seems wasteful. I think I'll tackle this two ways:

1) Allow reading from stdin on `userenum` and all the other subcommands by passing a `-`. That way you can still do bash sleep, but you only need to run kerbrute once:
```
while read user; do sleep 5; echo $user; done < usernames.lst | ./kerbrute -d lab.ropnop.com userenum -
```

2) I have no objections adding a global `-delay` option either. That would be pretty easy to add, just add a sleep before reading the next line if it's set. Would override the threads and just use a single thread probably

I'll try to get some PRs up for you to look at in the next week or so.

Thanks again!
