### ISSUE TITLE
error asni 1 sequence trucated

### ISSUE THREAD

**Issue by systemguy** [ropnop/kerbrute#28]
eviljon@spookysec.local - [Root cause: Encoding_Error] Encoding_Error: failed to unmarshal KDC's reply: asn1: syntax error: sequence truncated

**Comment by sec13b** [comment]
i have same error

┌──(kali㉿kali)-[~]
└─$ kerbrute userenum --dc=ABC-DC -d=abc.local /usr/share/wordlists/seclists/Usernames/xato-net-10-million-usernames.txt -v 

    
Version: v1.0.3 (9dad6e1) - 09/22/23 - Ronnie Flathers @ropnop

2023/09/22 12:06:29 >  Using KDC(s):
2023/09/22 12:06:29 >   ABC-DC:88


2023/09/22 12:07:09 >  [!] michael@abc.local - [Root cause: Encoding_Error] Encoding_Error: failed to unmarshal KDC's reply: asn1: syntax error: sequence truncated                                                                                                                                  
2023/09/22 12:07:09 >  [!] chris@abc.local - [Root cause: Encoding_Error] Encoding_Error: failed to unmarshal KDC's reply: asn1: syntax error: sequence truncated

**Comment by BrunoTeixeira1996** [comment]
@sec13b have you found why this is happening?

**Comment by sec13b** [comment]
nop
